
List <String> MAMAKSOTA = [
  'Dhugaan niqallatti malee hincittu',
   'Waliigalan alaa galan',
  'Dhugaan niqallatti malee hincittu',
  'Osoo gubadhuun kolfa jette akaayiin.'
 'Waaqni hinariifatu lafa jedhe hinoolu',
 'Jaamtu jaamti malee, saree ija hindhiqan.',
 'Qeerrensa eegee hinqaban qaban gad hin dhiisan.',
 'Kan qotiyyoon iyyuu male qacceen iyyiti.',
 'Hudduun guddateef dhuufuu hindhowwu.',
  'Garbittiin gargaarsa argatte majii dhoksiti.',
"Ni ta'a jennaan Harree qallee hin ta'u jennaan harree gannee isumaa fidaa jennaan dhaqnee dhabne.",
"Kan akka fardaa nyaatu gaafa akka namaatti nyaate du'a.",
"Garaacha dheedhii, garaatti beeki.",
"Midhaan warra raatuu bona bona nyaatu.",
"Haadha hin qabdu akkoof boossi.",
"Keessummaa qamalee raafuu keessatti argu.",
"Sareen sarbaa hin qabdu mukarbaa hin yaabbattu.",
"Gadheen qalbii hin qabdu kan darbe hin yaadatu.",
"Kan lafatti wal hintaane muka wajjiin hin koru.",
"Fincaan lukkuu kan arge haa himuu.",
"Durattuu durii maalayyaa waaqoo lama tahe.",
"Arruma salaattee arruma maraatte.",
"Yaanni karaa hin dhaleessu.",
"Qilleensarratti mana hin ijaaran.",
"Eeboo darbatanii jinfuu hin qabatani.",
"Akka cabanitti okkolan.",
"Ni turra malee ni urra jette boonbiin.",
"Alaa manatti galan.",
"Kokkolfaa nama nyaatti golfaan.",
"Waaqaan duuba karaan nama hin dabarsu.",
"Kan waaqa abdate hindhabu.",
"Kan waaq mure hinoolu.",
"Kan waaq uwwise hindaaru.",
"Namni niyaada;waaqni niguuta.",
"Ganamaan bahaniif waaqa jalaa hinbahan.",
"Katuffatantu ardaa dhaala",
"Bara barri argate buqqeetu dhagaa cabsa",
"Harreen fe'aa barbaaddu ufiin ooydaa dhufti	",
"Yaa soogidda ofii jettu mi'aayi ta'uu baannaan dhagaadha jadhanii si darbu",
"Kan qaban qaba hin guunnne gadhiisan bakkee guutti",
"Hindaaqqoon haate haatee halbee ittin qalamtu baasti",
"Tuulamanii taa’anii waaqa ofii hin komatan",
"Ofii jettu mi’aa’i yoo kaan dhagaa jadhanii sigatu jedhe",
"Alagaa fi dukkanatti ija hin baasan",
"Mana oormaa bareedaarra, godoo ofii wayya",
"Adala gowwoomsuun suuta suutan",
"Kan akka fardaa nyaatu gaafa waan nyaatu dhabe du'a	",
"Soogidda ofii jettu mi'aayi anaa jettu dhagaa tahi	",
"Kormi biyya ofiitti baroodu biyya ormaatti ni mar'ata	",
"Muka biyya jiruun mana ijaaran",
];

